#!/usr/bin/env bash

set -o pipefail

source ./utils.sh
source ./install-aws-cli.sh

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

echo "from main"
echo $DOTFILES_PATH
 # THEN PASS IN THE BREWFILE LOCATION...
# brew bundle --file "$DOTFILES_PATH/Brewfile"